### ISSUE TITLE
Variant effect prediction analysis

### ISSUE THREAD

**Issue by smruti241** [songlab-cal/gpn#10]
Hi @gonzalobenegas , I have gone through your paper. It's actually interesting. But I want to know how you are doing VEP analysis. what is the basis for that? why there is a need for masking? Most important part is using the different genomes. Thats why I am asking you the base of this concept.

**Comment by gonzalobenegas** [comment]
Hi! The approach is computing the conditional distribution of the nucleotide at a certain position in the genome, given its context, which requires masking. The hope is that by being trained on several sequences, including related species, the model can estimate which nucleotides can often appear in this context (benign) and which ones cannot (pathogenic).
