### ISSUE TITLE
Help with alternative set up

### ISSUE THREAD

**Issue by Michal-Babins** [songlab-cal/gpn#11]
Hey, 

Thanks for the work!

I am interested in training a model on viral sequences pulled from refseq. I see the the Snakemake workflow can take NCBI accessions, but pulls from NCBI Genome. 

I was wondering what the best method train the model on sequences coming from a fasta file format would be?

Looking through the run_mlm.py it looks like it's specific to a predefined format, my assumption is that the way forward will be to import the model for training and do the rest according to the data, but was wanted to check if you had any suggestions. 

Thanks, 
Michal

**Comment by gonzalobenegas** [comment]
Hi! Thanks for your interest. I'll upload an example in a couple of days and let you know.

**Comment by gonzalobenegas** [comment]
Hey, just updated the READMEs with more information on how to train with your own set of fasta files. Any feedback welcome!

**Comment by Michal-Babins** [comment]
Thank you for the update! 

One question I do have is for training, here `--dataset_name results/dataset` is where the fasta file would be passed? Is there also a header format that's expected?

Thanks!

**Comment by gonzalobenegas** [comment]
Hi! `results/dataset` is the output of running [this pipeline](https://github.com/songlab-cal/gpn/tree/main/workflow/make_dataset).

**Comment by Michal-Babins** [comment]
Thank you for clarifying! Once I get time to try this out, I will let you know how it goes. Thanks again.

**Comment by Michal-Babins** [comment]
Hey @gonzalobenegas, getting around to trying this out with the example data and I hit this:

```
10/12/2023 14:44:59 - WARNING - __main__ - Process rank: 0, device: cuda:0, n_gpu: 1distributed training: True, 16-bits training: True
{'train': <datasets.iterable_dataset.IterableDataset object at 0x155491869b90>, 'validation': <datasets.iterable_dataset.IterableDataset object at 0x155491869c90>, 'test': <datasets.iterable_dataset.IterableDataset object at 0x155491869dd0>}
10/12/2023 14:44:59 - WARNING - __main__ - You are instantiating a new config instance from scratch.
/home/mbabinski/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py:557: UserWarning: This DataLoader will create 16 worker processes in total. Our suggested max number of worker in current system is 6, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
wandb: ERROR api_key not configured (no-tty). call wandb.login(key=[your_api_key])
Traceback (most recent call last):
  File "/cm/local/apps/python3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/cm/local/apps/python3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mbabinski/.local/lib/python3.7/site-packages/gpn/ss/run_mlm.py", line 564, in <module>
    main()
  File "/home/mbabinski/.local/lib/python3.7/site-packages/gpn/ss/run_mlm.py", line 502, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/mbabinski/.local/lib/python3.7/site-packages/transformers/trainer.py", line 1649, in train
    ignore_keys_for_eval=ignore_keys_for_eval,
  File "/home/mbabinski/.local/lib/python3.7/site-packages/transformers/trainer.py", line 1862, in _inner_training_loop
    self.control = self.callback_handler.on_train_begin(args, self.state, self.control)
  File "/home/mbabinski/.local/lib/python3.7/site-packages/transformers/trainer_callback.py", line 353, in on_train_begin
    return self.call_event("on_train_begin", args, state, control)
  File "/home/mbabinski/.local/lib/python3.7/site-packages/transformers/trainer_callback.py", line 407, in call_event
    **kwargs,
  File "/home/mbabinski/.local/lib/python3.7/site-packages/transformers/integrations.py", line 771, in on_train_begin
    self.setup(args, state, model, **kwargs)
  File "/home/mbabinski/.local/lib/python3.7/site-packages/transformers/integrations.py", line 747, in setup
    **init_args,
  File "/home/mbabinski/.local/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 1189, in init
    raise e
  File "/home/mbabinski/.local/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 1166, in init
    wi.setup(kwargs)
  File "/home/mbabinski/.local/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 313, in setup
    _entity=kwargs.get("entity") or settings.entity,
  File "/home/mbabinski/.local/lib/python3.7/site-packages/wandb/sdk/wandb_login.py", line 298, in _login
    wlogin.prompt_api_key()
  File "/home/mbabinski/.local/lib/python3.7/site-packages/wandb/sdk/wandb_login.py", line 228, in prompt_api_key
    raise UsageError("api_key not configured (no-tty). call " + directive)
wandb.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])
```

**Comment by gonzalobenegas** [comment]
Sounds like an issue with [wandb](https://wandb.ai/), used for tracking metrics. You can disable it by replacing `--report_to wandb` with `--report_to none`. However, I'd recommend you [create a wandb account and login](https://docs.wandb.ai/quickstart).

**Comment by Michal-Babins** [comment]
Got it, thank you. 

Also, for downloading data from ncbi or custom databases, does the assembly.tsv need to be formatted the same or can it just be a list of accessions?

**Comment by gonzalobenegas** [comment]
For downloading data from NCBI:
- First column must be NCBI accession (tested on RefSeq, not sure it works on GenBank but it might)

With your own fastas:
- First column (let's call it `{assembly}`) must match the location of the fasta using the pattern `results/genome/{assembly}.fa.gz`. Optionally match `results/annotation/{assembly}.gff.gz` if you want to use an annotation for filtering regions. 

Other columns are not used.

**Comment by Michal-Babins** [comment]
Thanks. Resolved a few things and got it running now. Got a memory error, but this is due to an old GPU node. I will need to move data to a better machine and try again. 
Will probably test again on Monday. Happy to record my steps to help others who may want to train with custom data. Thanks!

**Comment by gonzalobenegas** [comment]
Thanks, for sure your experience is very helpful, and sorry for all the little details that are not yet documented!
