### ISSUE TITLE
Tokenizer for gpn-msa-sapiens

### ISSUE THREAD

**Issue by IandRover** [songlab-cal/gpn#15]
Hello,

Firstly, I want to express my appreciation for your remarkable work. It's been very helpful in my projects. 

However, I recently encountered an issue while trying to use the tokenizer of GPN. The problem arises when I try to use the following code snippet:
```
from transformers import AutoTokenizer
TOKENIZER_PATH = "songlab/gpn-msa-sapiens"
tokenizer = AutoTokenizer.from_pretrained(TOKENIZER_PATH)
```
The error is 
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[13], line 5
      3 TOKENIZER_PATH = "songlab/gpn-msa-sapiens"
      4 # TOKENIZER_PATH = "songlab/gpn-brassicales"
----> 5 tokenizer = AutoTokenizer.from_pretrained(TOKENIZER_PATH)

File ~/.conda/envs/H3/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py:708, in AutoTokenizer.from_pretrained(cls, pretrained_model_name_or_path, *inputs, **kwargs)
    706 if config_tokenizer_class is None:
    707     if not isinstance(config, PretrainedConfig):
--> 708         config = AutoConfig.from_pretrained(
    709             pretrained_model_name_or_path, trust_remote_code=trust_remote_code, **kwargs
    710         )
    711     config_tokenizer_class = config.tokenizer_class
    712     if hasattr(config, "auto_map") and "AutoTokenizer" in config.auto_map:

File ~/.conda/envs/H3/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py:1042, in AutoConfig.from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
   1040     return config_class.from_pretrained(pretrained_model_name_or_path, **kwargs)
   1041 elif "model_type" in config_dict:
-> 1042     config_class = CONFIG_MAPPING[config_dict["model_type"]]
   1043     return config_class.from_dict(config_dict, **unused_kwargs)
   1044 else:
   1045     # Fallback: use pattern matching on the string.
   1046     # We go from longer names to shorter names to catch roberta before bert (for instance)

File ~/.conda/envs/H3/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py:737, in _LazyConfigMapping.__getitem__(self, key)
    735     return self._extra_content[key]
    736 if key not in self._mapping:
--> 737     raise KeyError(key)
    738 value = self._mapping[key]
    739 module_name = model_type_to_module_name(key)

KeyError: 'GPNRoFormer'
```

I wonder if the model `songlab/gpn-msa-sapiens` have a corresponding unique tokenizer? If not, is it feasible to use the tokenizer from `songlab/gpn-brassicales` as an alternative for this task? In other words, are the tokenizers the same across GPN's work?

Thank you for your assistance and I look forward to your guidance on resolving this issue.

Best regards,
Chia-Hsiang Kao

**Comment by gonzalobenegas** [comment]
Hi, thank you for the kind words!

`songlab/gpn-msa-sapiens` is a GPN-MSA model, which does not have a tokenizer based on the HF Tokenizer library. The reason is that it uses an MSA rather than a sequence, so we decided to write [its own tokenizer from scratch](https://github.com/songlab-cal/gpn/blob/c22e640bb9f971c8041810d3cb22976fa3deb406/gpn/data.py#L511C20-L511C20). This is very simple and designed to work with n-dimensional byte arrays.

In general, you would interface with the model following [this example](https://github.com/songlab-cal/gpn/blob/main/examples/msa/basic_example.ipynb).

**Comment by HelloWorldLTY** [comment]
Hi, thansk for your work. I think it will be really helpful if you directly support a tokenizer from dna sequence, which is free from the version of reference genome. Thanks a lot.

**Comment by gonzalobenegas** [comment]
Hi! The [GPN-MSA tokenizer](https://github.com/songlab-cal/gpn/blob/05b23c54c572813810c094b31031901f7109575b/gpn/data.py#L511) does not depend on any reference genome, what strongly depends on the reference genome is the MSA.
