### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by dahaigui** [songlab-cal/gpn#16]
When I running Variant effect prediction, I had the following problem.

![image](https://github.com/songlab-cal/gpn/assets/47802187/269736c8-e86f-48fd-89c0-656634fd70c1)

How should I address this problem?

**Comment by dahaigui** [comment]
Maybe the Scaffold is too short?

**Comment by gonzalobenegas** [comment]
That's the most likely cause - sorry for the trouble!

I've been usually first filtering the input vcf by removing the positions within window_size//2 of the scaffold borders. This are just a handful in my experience since I've been using chromosome-level assemblies.

However, if you really want to score those positions, you would have to modify the script. One possibility is to pad with [PAD] token, but this is not usually used during training (at least in the official script) so it might confuse the model. Haven't tried though. Another approach is to modify the script so that in scaffold edge cases it does not take a symmetrical window around a position, but a skewed one so it doesn't go overboard.

**Comment by dahaigui** [comment]
I just got the result file `20S0008_clean.snp_filtered_B9008.splited.vcf.parquet`, how can I view its contents?

**Comment by gonzalobenegas** [comment]
In Python you can do:
```python
import pandas as pd

scores = pd.read_parquet("20S0008_clean.snp_filtered_B9008.splited.vcf.parquet")
```

**Comment by dahaigui** [comment]
Got it! Thank you very much!

**Comment by dahaigui** [comment]
Is this result file sorted by the position in the vcf file I provided?
I have annotated my vcf file using snpEFF and got some stop_gained variants, but these variants have bigger scores in gpn's variant effect prediction results, while some intergenic_region variants have smaller scores, as shown below.

**Stop_gained**, the result of snpEFF is `A01     2901768 .       G       A       211.64  PASS    AC=1;AF=0.500;AN=2;BaseQRankSum=0.874;DP=14;ExcessHet=3.0103;FS=0.000;MLEAC=1;MLEAF=0.500;MQ=60.00;MQRankSum=0.00;QD=15.12;ReadPosRankSum=0.125;SOR=1.179;ANN=A|stop_gained|HIGH|A01p05970.1_BraCCA|A01p05970.1_BraCCA|transcript|A01p05970.1_BraCCA.m1|protein_coding|2/4|c.697C>T|p.Gln233*|697/1122|697/1122|233/373||,A|upstream_gene_variant|MODIFIER|A01p05980.1_BraCCA|A01p05980.1_BraCCA|transcript|A01p05980.1_BraCCA.m1|protein_coding||c.-1868G>A|||||1868|,A|upstream_gene_variant|MODIFIER|A01p05990.1_BraCCA|A01p05990.1_BraCCA|transcript|A01p05990.1_BraCCA.m1|protein_coding||c.-3842G>A|||||3842|,A|downstream_gene_variant|MODIFIER|A01p05960.1_BraCCA|A01p05960.1_BraCCA|transcript|A01p05960.1_BraCCA.m1|protein_coding||c.*945G>A|||||945|;LOF=(A01p05970.1_BraCCA|A01p05970.1_BraCCA|1|1.00);NMD=(A01p05970.1_BraCCA|A01p05970.1_BraCCA|1|1.00)  GT:AD:DP:GQ:PL  0/1:6,8:14:99:219,0,136`, while result of gpn vep score is 0.44310555. 

**Intergenic_region**, the result of snpEFF is `A01     12314027        .       A       G       57.64   MQ40;QD2;SOR3   AC=1;AF=0.500;AN=2;BaseQRankSum=0.317;DP=161;ExcessHet=3.0103;FS=32.638;MLEAC=1;MLEAF=0.500;MQ=28.85;MQRankSum=-1.815e+00;QD=1.34;ReadPosRankSum=2.57;SOR=3.912;ANN=G|intergenic_region|MODIFIER|A01p22380.1_BraCCA-A01p22390.1_BraCCA|A01p22380.1_BraCCA-A01p22390.1_BraCCA|intergenic_region|A01p22380.1_BraCCA-A01p22390.1_BraCCA|||n.12314027A>G||||||      GT:AD:DP:GQ:PL  0/1:36,7:66:65:65,0,1202`, while result of gpn vep score is -4.8882227.

Is this a problem with the way it's sorted, or is there something else going on?

**Comment by gonzalobenegas** [comment]
The result file should have the same order as the input file.

Indeed it's surprising the stop gained has a higher score than intergenic region. Is this a general pattern? What about missense, for example?

I'd be happy to try help more either here or in private.

**Comment by dahaigui** [comment]
The missense is ```
A01     395168  .       C       T       125.64  PASS    AC=1;AF=0.500;AN=2;BaseQRankSum=-5.300e-02;DP=19;ExcessHet=3.0103;FS=4.561;MLEAC=1;MLEAF=0.500;MQ=60.00;MQRankSum=0.00;QD=6.98;ReadPosRankSum=-8.800e-02;SOR=1.170;ANN=T|missense_variant|MODERATE|A01p00810.1_BraCCA|A01p00810.1_BraCCA|transcript|A01p00810.1_BraCCA.m1|protein_coding|15/15|c.1990G>A|p.Val664Ile|1990/2082|1990/2082|664/693||WARNING_TRANSCRIPT_MULTIPLE_STOP_CODONS,T|downstream_gene_variant|MODIFIER|A01p00800.1_BraCCA|A01p00800.1_BraCCA|transcript|A01p00800.1_BraCCA.m1|protein_coding||c.*4357C>T|||||4357|,T|downstream_gene_variant|MODIFIER|A01p00820.1_BraCCA|A01p00820.1_BraCCA|transcript|A01p00820.1_BraCCA.m1|protein_coding||c.*3853G>A|||||3853| GT:AD:DP:GQ:PL  0/1:13,5:19:99:133,0,441
A01     396514  .       G       A       157.64  PASS    AC=1;AF=0.500;AN=2;BaseQRankSum=1.53;DP=14;ExcessHet=3.0103;FS=0.000;MLEAC=1;MLEAF=0.500;MQ=57.83;MQRankSum=-2.205e+00;QD=11.26;ReadPosRankSum=0.450;SOR=0.905;ANN=A|splice_region_variant&synonymous_variant|LOW|A01p00810.1_BraCCA|A01p00810.1_BraCCA|transcript|A01p00810.1_BraCCA.m1|protein_coding|11/15|c.991C>T|p.Leu331Leu|991/2082|991/2082|331/693||WARNING_TRANSCRIPT_MULTIPLE_STOP_CODONS,A|downstream_gene_variant|MODIFIER|A01p00820.1_BraCCA|A01p00820.1_BraCCA|transcript|A01p00820.1_BraCCA.m1|protein_coding||c.*2507C>T|||||2507|    GT:AD:DP:GQ:PGT:PID:PL:PS       0|1:9,5:14:99:0|1:396514_G_A:165,0,363:396514
```
 ,the score of the position is 2.5295594

**Comment by gonzalobenegas** [comment]
A good way to assess whether this is a general pattern might be to gather at least n=30 variants from each type and plot their mean scores (or their distribution).

**Comment by dahaigui** [comment]
I just calculated the mean scores of different variant types, the result is
![image](https://github.com/songlab-cal/gpn/assets/47802187/9c96257a-c24a-40f2-a358-bf022d60e140)

**Comment by dahaigui** [comment]
Thank you for your reply! 


I am more than happy to communicate with you about this project, the model was trained on Brassica rapa (similar to Brassica oleracea) and the VEP was run on its mutant. I used the ConvNet, but I'm not sure what the number of iterations is.


The output log file and wandb charts are in the attachment.


Looking forward for your reply!


| |
陈海旭
|
|
***@***.***
|
---- Replied Message ----
| From | Gonzalo ***@***.***> |
| Date | 12/8/2023 02:21 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [songlab-cal/gpn] IndexError: tuple index out of range (Issue #16) |

Thanks. Doesn't seem like this model has learned anything. I could provide some guidance with the following information:

What species was the model trained on?
What species is the model running VEP on?
What is the architecture and number of iterations? I guess would help to inspect the validation loss curve as well.
I'd be happy to take this into a private conversation if you prefer.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

  0%|          | 0/120000 [00:00<?, ?it/s]/home/chenhx/miniconda3/envs/GPN/lib/python3.8/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '










































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































  8%|▊         | 10000/120000 [4:03:22<40:59:28,  1.34s/it]/home/chenhx/miniconda3/envs/GPN/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py:33: UserWarning:
    There is an imbalance between your GPUs. You may want to exclude GPU 2 which
    has less than 75% of the memory or cores of GPU 0. You can do so by setting
    the device_ids argument to DataParallel, or by setting the CUDA_VISIBLE_DEVICES
    environment variable.
  warnings.warn(imbalance_warn.format(device_ids[min_pos], device_ids[max_pos]))
{'loss': 1.0029, 'learning_rate': 0.001, 'epoch': 2.01}
  8%|▊         | 10000/120000 [4:06:10<40:59:28,  1.34s/it]
  8%|▊         | 10000/120000 [4:06:10<40:59:28,  1.34s/it]/home/chenhx/miniconda3/envs/GPN/lib/python3.8/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '





























































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































 17%|█▋        | 19999/120000 [8:09:51<37:55:21,  1.37s/it]
 17%|█▋        | 20000/120000 [8:09:52<38:48:00,  1.40s/it]/home/chenhx/miniconda3/envs/GPN/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py:33: UserWarning:
    There is an imbalance between your GPUs. You may want to exclude GPU 2 which
    has less than 75% of the memory or cores of GPU 0. You can do so by setting
    the device_ids argument to DataParallel, or by setting the CUDA_VISIBLE_DEVICES
    environment variable.
  warnings.warn(imbalance_warn.format(device_ids[min_pos], device_ids[max_pos]))
 17%|█▋        | 20000/120000 [8:12:43<38:48:00,  1.40s/it]
 17%|█▋        | 20000/120000 [8:12:43<38:48:00,  1.40s/it]/home/chenhx/miniconda3/envs/GPN/lib/python3.8/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '




















































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































 25%|██▌       | 30000/120000 [12:01:05<34:29:48,  1.38s/it]/home/chenhx/miniconda3/envs/GPN/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py:33: UserWarning:
    There is an imbalance between your GPUs. You may want to exclude GPU 2 which
    has less than 75% of the memory or cores of GPU 0. You can do so by setting
    the device_ids argument to DataParallel, or by setting the CUDA_VISIBLE_DEVICES
    environment variable.
  warnings.warn(imbalance_warn.format(device_ids[min_pos], device_ids[max_pos]))
{'loss': 0.8753, 'learning_rate': 0.001, 'epoch': 7.01}
{'eval_loss': 1.0130711442071016, 'eval_runtime': 170.6429, 'eval_samples_per_second': 1025.498, 'eval_steps_per_second': 2.004, 'epoch': 7.01}
 25%|██▌       | 30000/120000 [12:03:55<34:29:48,  1.38s/it]/home/chenhx/miniconda3/envs/GPN/lib/python3.8/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '























































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































 33%|███▎      | 40000/120000 [15:52:26<30:36:39,  1.38s/it]/home/chenhx/miniconda3/envs/GPN/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py:33: UserWarning:
    There is an imbalance between your GPUs. You may want to exclude GPU 2 which
    has less than 75% of the memory or cores of GPU 0. You can do so by setting
    the device_ids argument to DataParallel, or by setting the CUDA_VISIBLE_DEVICES
    environment variable.
  warnings.warn(imbalance_warn.format(device_ids[min_pos], device_ids[max_pos]))
{'loss': 0.8591, 'learning_rate': 0.001, 'epoch': 9.02}
 33%|███▎      | 40000/120000 [15:55:17<30:36:39,  1.38s/it]/home/chenhx/miniconda3/envs/GPN/lib/python3.8/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
{'eval_loss': 1.0026764534473793, 'eval_runtime': 171.2415, 'eval_samples_per_second': 1021.914, 'eval_steps_per_second': 1.997, 'epoch': 9.02}















































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































 42%|████▏     | 49999/120000 [19:44:32<26:30:40,  1.36s/it]
 42%|████▏     | 50000/120000 [19:44:33<26:28:54,  1.36s/it]/home/chenhx/miniconda3/envs/GPN/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py:33: UserWarning:
    There is an imbalance between your GPUs. You may want to exclude GPU 2 which
    has less than 75% of the memory or cores of GPU 0. You can do so by setting
    the device_ids argument to DataParallel, or by setting the CUDA_VISIBLE_DEVICES
    environment variable.
  warnings.warn(imbalance_warn.format(device_ids[min_pos], device_ids[max_pos]))
 42%|████▏     | 50000/120000 [19:47:25<26:28:54,  1.36s/it]
 42%|████▏     | 50000/120000 [19:47:25<26:28:54,  1.36s/it]/home/chenhx/miniconda3/envs/GPN/lib/python3.8/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '

























































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































 50%|████▉     | 59999/120000 [23:34:54<22:28:44,  1.35s/it]
 50%|█████     | 60000/120000 [23:34:55<22:27:51,  1.35s/it]/home/chenhx/miniconda3/envs/GPN/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py:33: UserWarning:
    There is an imbalance between your GPUs. You may want to exclude GPU 2 which
    has less than 75% of the memory or cores of GPU 0. You can do so by setting
    the device_ids argument to DataParallel, or by setting the CUDA_VISIBLE_DEVICES
    environment variable.
  warnings.warn(imbalance_warn.format(device_ids[min_pos], device_ids[max_pos]))
{'eval_loss': 0.9871725452593159, 'eval_runtime': 168.573, 'eval_samples_per_second': 1038.09, 'eval_steps_per_second': 2.029, 'epoch': 14.01}
 50%|█████     | 60000/120000 [23:37:44<22:27:51,  1.35s/it]/home/chenhx/miniconda3/envs/GPN/lib/python3.8/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































 58%|█████▊    | 69999/120000 [27:23:19<18:59:12,  1.37s/it]
 58%|█████▊    | 70000/120000 [27:23:20<18:52:58,  1.36s/it]/home/chenhx/miniconda3/envs/GPN/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py:33: UserWarning:
    There is an imbalance between your GPUs. You may want to exclude GPU 2 which
    has less than 75% of the memory or cores of GPU 0. You can do so by setting
    the device_ids argument to DataParallel, or by setting the CUDA_VISIBLE_DEVICES
    environment variable.
  warnings.warn(imbalance_warn.format(device_ids[min_pos], device_ids[max_pos]))
 58%|█████▊    | 70000/120000 [27:26:09<18:52:58,  1.36s/it]
 58%|█████▊    | 70000/120000 [27:26:09<18:52:58,  1.36s/it]/home/chenhx/miniconda3/envs/GPN/lib/python3.8/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '



















































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































 67%|██████▋   | 79999/120000 [31:13:38<14:59:56,  1.35s/it]
 67%|██████▋   | 80000/120000 [31:13:40<15:00:20,  1.35s/it]/home/chenhx/miniconda3/envs/GPN/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py:33: UserWarning:
    There is an imbalance between your GPUs. You may want to exclude GPU 2 which
    has less than 75% of the memory or cores of GPU 0. You can do so by setting
    the device_ids argument to DataParallel, or by setting the CUDA_VISIBLE_DEVICES
    environment variable.
  warnings.warn(imbalance_warn.format(device_ids[min_pos], device_ids[max_pos]))
{'eval_loss': 0.9766971745027024, 'eval_runtime': 168.2876, 'eval_samples_per_second': 1039.851, 'eval_steps_per_second': 2.032, 'epoch': 19.0}
 67%|██████▋   | 80000/120000 [31:16:28<15:00:20,  1.35s/it]/home/chenhx/miniconda3/envs/GPN/lib/python3.8/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '

**Comment by dahaigui** [comment]
I'd happy to take this into a private conversation. Email me at dahaiguilalala@163.com!
