### ISSUE TITLE
ignore_data_skip error

### ISSUE THREAD

**Issue by liuyq123** [songlab-cal/gpn#2]
Hi, I got an error when running `train_512_convnet_only_athaliana.sh`: `run_mlm_custom.py: error: argument --ignore_data_skip: Truthy value expected: got \ but expected one of yes/no, true/false, t/f, y/n, 1/0 (case insensitive)`. So I changed the \ after `--ignore_data_skip` to 0 or 1. But that case I got connection error:
<img width="1077" alt="Screen Shot 2022-10-10 at 6 45 00 PM" src="https://user-images.githubusercontent.com/47292066/194963159-3e5ac9c1-fcd8-42da-bbad-8e0dcbb0d5ca.png">

Thank you!

**Comment by gonzalobenegas** [comment]
Sorry the code is not just working out of the box (I'm on it).

If you run `data/mlm/train_tokenizer_bare.py` then that error should disappear.

**Comment by liuyq123** [comment]
Thank you! That works
