### ISSUE TITLE
Discrepancy in ClinVar Pathogenic Variant Counts: Paper vs. Hugging Face Dataset  

### ISSUE THREAD

**Issue by yangzhao1230** [songlab-cal/gpn#20]
There seems to be a discrepancy in the number of ClinVar pathogenic variants reported in the associated paper and the dataset available on Hugging Face. According to the paper, there are 21,275 pathogenic variants listed, whereas the Hugging Face dataset contains 22,254 such entries.

**Comment by yangzhao1230** [comment]
I have noticed an inconsistency in the reported number of variants across multiple datasets. Specifically, the Hugging Face repository consistently shows a higher number of variants.

**Comment by gonzalobenegas** [comment]
Hi! There's an additional filter to remove variants where one of the benchmarked methods has NaN. [This self-contained Colab notebook](https://colab.research.google.com/drive/183eH_xdF9xeBbcyCIKBYAMOWIPbYuEf7?usp=sharing) shows how to get the exact number of variants for ClinVar. It's similar for other datasets, you might want to check [our notebook](https://github.com/songlab-cal/gpn/blob/main/analysis/human/workflow/notebooks/vep.ipynb).
