### ISSUE TITLE
Why Bidirectional LLR Calculation and Averaging

### ISSUE THREAD

**Issue by yangzhao1230** [songlab-cal/gpn#21]
Hello,  

I've been examining the implementation of the Log Likelihood Ratio (LLR) calculation in the MLMforVEPModel, and I noticed that the LLR is computed separately for both forward (`fwd`) and reverse (`rev`) sequences. Any clarification or insights into the methodology would be greatly appreciated

**Comment by gonzalobenegas** [comment]
Hi! This serves two purposes:
* Ensures reverse-complement invariance (the choice of strand is arbitrary so we don't want the variant score to vary between them)
* Averaging the two predictions is a form of "ensembling" and could improve performance (we haven't checked though)

For more discussions about the topic, I recommend [Towards a Better Understanding of Reverse-Complement Equivariance for Deep Learning Models in Genomics](https://proceedings.mlr.press/v165/zhou22a.html).
