### ISSUE TITLE
Cannot run vep.ipynb (variant effect prediction)

### ISSUE THREAD

**Issue by raphaelmourad** [songlab-cal/gpn#22]
Hi,

great repo! 

I would like to run the vep.ipynb notebook, but I get the following errors:
![image](https://github.com/songlab-cal/gpn/assets/23706206/7ec95c80-66b6-495e-b45c-d4b389c1619b)

Where can I find the folder corresponding to "../../results/preds/songlab"?

Raf

**Comment by gonzalobenegas** [comment]
Hi, thank you for your interest!

While all these variants and predictions are available on [Huggingface](https://huggingface.co/datasets/songlab/human_variants), this notebook relies on all the predictions being available in the local machine in certain paths. All the predictions can be obtained from scratch by running this [Snakefile](https://github.com/songlab-cal/gpn/blob/main/analysis/human/workflow/Snakefile), but would probably take a lot of time (and might need to comment/uncomment some stuff as is right now). In the future I can upload all my local directory with all the intermediate results, but I'll probably try to wait until the paper is accepted.

I'd say the easiest way to run this notebook right now would be to replace that cell with the error with:
```python
V = pd.read_parquet("hf://datasets/songlab/human_variants/variants_and_preds.parquet")
```
You won't be able to run the specific part that relies on `V_enformer`.

**Comment by raphaelmourad** [comment]
Ok Thank you!

**Comment by ddofer** [comment]
Hi - I am working on replicating your results (ideally phyloGPN, as it's fastest/simplest) with clinvar. Anynews on your intermediate data and exact eval code being uploaded? Thanks!

**Comment by gonzalobenegas** [comment]
Hi, @cralbors might be able to help
