### ISSUE TITLE
the Increased Number of Entries in the Updated VEP Dataset on Hugging Face

### ISSUE THREAD

**Issue by yangzhao1230** [songlab-cal/gpn#25]
Hi! Thanks for your quick reply! I've noticed that you've uploaded a curated version of the VEP dataset on Hugging Face. However, I see that there's more data here than before. Could you explain this situation? For example, your newly organized dataset at https://huggingface.co/datasets/songlab/clinvar has about 400K entries, which is more than the total number before.

**Comment by gonzalobenegas** [comment]
Hi! There are slight differences from the previous versions, which will be documented in version 2 of our preprint, to be uploaded in the next weeks.

The ClinVar dataset should have around 40K entries, I believe, not 400K.
