### ISSUE TITLE
Use multiple GPUs for training

### ISSUE THREAD

**Issue by liuyq123** [songlab-cal/gpn#3]
Hi, I want to use multiple GPUs for training, so I added `n_gpu`  to `train_512_convnet_only_athaliana.sh`, but I got an error:

<img width="966" alt="Screen Shot 2022-10-14 at 2 31 43 PM" src="https://user-images.githubusercontent.com/47292066/195916595-5819f430-d5bb-496b-a30c-cda0302724ed.png">

Can you tell me how to use multiple GPUs to train this model?

Thank you! And sorry for so many questions.

**Comment by gonzalobenegas** [comment]
Hey, I'm happy to answer any questions and it's helpful for me to improve the code and documentation in the future.

By default, all detected GPUs will be used. If you want to subset to fewer GPUs, for example number 0 and 2, you can run `CUDA_VISIBLE_DEVICES=0,2 bash train_512_convnet_only_athaliana.sh`.

The script uses the Huggingface Trainer, you can read more about its arguments [here](https://huggingface.co/docs/transformers/main_classes/trainer#transformers.TrainingArguments).

**Comment by liuyq123** [comment]
Thank you for your quick response! 

I just checked and yes in default all GPUs selected are used. I read in your manuscript that you used 4 2080ti GPUs, and I'm using 4 same GPUs, but somehow I kept getting `RuntimeError: Unable to find a valid cuDNN algorithm to run convolution` until I decreased `per_device_train_batch_size` to a very small number, so I assumed that it used only one. Sorry for not checking it carefully enough. 

Btw, is 250 the batch size you used for training?

**Comment by gonzalobenegas** [comment]
We used 250*4 gpus = 1000 batch size. How small is the batch size you are using to avoid the error? I wonder if it's just an installation issue.

PS. I have a suspicion in how Huggingface trainer handles torch.utils.data.IterableDataset and the actual batch size would have been 250 instead of 1000. In the next release of gpn we are not using IterableDataset any more so it shouldn't be a problem.

**Comment by liuyq123** [comment]
I used 4.

I noticed that if I reduced the batch size to 1, then only 1 GPU would run. This probably confirms your suspicion.

Thank you!

**Comment by gonzalobenegas** [comment]
Thank you, that's helpful to know!

I think you might have an installation problem, I would try creating a new conda environment, installing torch with conda as recommended on https://pytorch.org/, and only then installing gpn with pip.
