### ISSUE TITLE
Questions about reproducing results in the manuscript

### ISSUE THREAD

**Issue by HelloWorldLTY** [songlab-cal/gpn#31]
Hi, thanks for your great work. I wonder how to reproduce the figure results you showed in Fig. 2A. How to access the region labels? Thanks a lot!

**Comment by gonzalobenegas** [comment]
Hi, thanks for your interest! The notebook used for plotting is [here](https://github.com/songlab-cal/gpn/blob/main/analysis/arabidopsis/embedding_umap.ipynb). All intermediate results from the paper can be downloaded from [here](https://huggingface.co/datasets/gonzalobenegas/processed-data-arabidopsis) (e.g. see [here](https://huggingface.co/datasets/gonzalobenegas/processed-data-arabidopsis/tree/main/embedding) for embedding-related stuff).

**Comment by HelloWorldLTY** [comment]
Hi, maybe the last question. You claimed that the embeddings are computed based on reference genome, but you had 8 different reference genome for different speices. Therefore, I wonder if I can access the information of the reference genome you used. Thanks a lot!

**Comment by gonzalobenegas** [comment]
We use the Arabidopsis reference genome, specifically:
`FASTA_URL: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/735/GCF_000001735.4_TAIR10.1/GCF_000001735.4_TAIR10.1_genomic.fna.gz"
`
