### ISSUE TITLE
Do you have pre-trained GPN for different genomes?

### ISSUE THREAD

**Issue by gdolsten** [songlab-cal/gpn#4]
E.g. GPN for Mouse, human, D. Mel?

**Comment by gonzalobenegas** [comment]
Hi! Not yet but we'll let you know!

**Comment by gabedolpten** [comment]
So it is only trained for arabidopsis currently?

**Comment by genecell** [comment]
Looking forward to mouse and human genomes too! I could help train them if needed.

**Comment by gonzalobenegas** [comment]
Thank you for your interest! It's been quite challenging to obtain good results in human but we are making significant progress! It will still be a few months out... Once we have a good recipe for human it should be easier to port into other complex genomes.

**Comment by gonzalobenegas** [comment]
Hello! We've recently released a human model, although it's with the alignment-based version (GPN-MSA).  You can see details in the README.

**Comment by genecell** [comment]
Sounds good! Thanks for sharing and letting us know.
