### ISSUE TITLE
How to generate the missing output files

### ISSUE THREAD

**Issue by wokkel** [songlab-cal/gpn#8]
Hi,
I'd love to learn more about this and therefore wanted to run the Jupyter notebooks in the Arabidopsis folder.
However, these depend on artifacts in an output folder.
How can I get these artifacts or how can I generate them?

Regards,
Harald

**Comment by gonzalobenegas** [comment]
Hi Harald,
Thanks for your interest! In general you could run `snakemake --cores all <artifact>`. It can take a fair amount of time though, let me try to upload some of the intermediate files.
Best,
Gonzalo

**Comment by gonzalobenegas** [comment]
I've uploaded the files here:
https://huggingface.co/datasets/gonzalobenegas/processed-data-arabidopsis/tree/main
Let me know if there's anything missing I could add.

**Comment by wokkel** [comment]
Thank you for the quick response.
Much appreciated.
