### ISSUE TITLE
GPN for covid genome

### ISSUE THREAD

**Issue by smruti241** [songlab-cal/gpn#9]
Can you please tell me how I can use gpn code for covid genome?

**Comment by gonzalobenegas** [comment]
Hello! You could try adapting the code here:
https://github.com/songlab-cal/gpn/tree/main/workflow/make_dataset_from_ncbi

GPN is still experimental and there are so many design choices. At this stage applying it to a new genome probably takes quite a bit of experimentation.  One piece of advice would be to train on a diverse set of viruses, not just Covid strains.
